//All Items
export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const GET_ALL_ITEMS_SUCCESS = "GET_ALL_ITEMS_SUCCESS";
export const GET_ALL_ITEMS_FAILURE = "GET_ALL_ITEMS_FAILURE";
export const SET_FILTERED_DATA = "SET_FILTERED_DATA";
export const SET_SEARCH_FILTERED = "SET_SEARCH_FILTERED";

//Cart
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";

//selected Items
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const CLOSE_CUSTOMISE_MODAL = "CLOSE_CUSTOMISE_MODAL";
